parameters:
#    pc_presentation.example.class: PC\PresentationBundle\Example

services:
#    pc_presentation.example:
#        class: %pc_presentation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
